### ISSUE TITLE
GCP安装脚本，显示下载失败。

### ISSUE THREAD

**Issue by orrzz** [233boy/UDPspeeder#3]
不知道怎么回事，请帮解答一下

**Comment by 233boy** [comment]
您好，真的很抱歉，是我修改了用户名的原因，现在已经更新了，请重新尝试一下，是否已经能正常工作？

**Comment by syfjhz22** [comment]
巨巨，看了一下似乎是因为UDPspeeder/releases/latest现在是 v1@20171116.0，而不是v2@20171116.0，导致下载失败，请问能修正一下吗？

**Comment by 233boy** [comment]
@syfjhz22 
你是直接 clone 吗？

**Comment by orrzz** [comment]
感谢回答，但依然显示下载错误，不解
`Reading package lists... Done
Building dependency tree
Reading state information... Done
wget is already the newest version (1.18-5+deb9u1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
--2017-11-18 13:31:57--  https://github.com/wangyu-/UDPspeeder/releases/download/v1@20171116.0/speederv2_binaries.tar.gz
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-11-18 13:31:57 ERROR 404: Not Found.

 下载 UDPspeeder 失败！`

**Comment by 233boy** [comment]
请问解决问题了吗？
重新使用安装 命令 执行看看？我这边测试没有问题了
```
bash <(curl -s -L https://233abc.com/UDPspeeder.sh)
```

**Comment by orrzz** [comment]
已解决，正在研究如何配置，多谢
