### ISSUE TITLE
下载 UDPspeeder 失败！

### ISSUE THREAD

**Issue by zugust** [233boy/UDPspeeder#4]
........... UDPspeeder 快速一键安装 by 233abc.com ..........

帮助说明: https://233abc.com/post/20/

 1. 安装

 2. 卸载

请选择[1-2]:1
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Package wget-1.14-15.el7_4.1.x86_64 already installed and latest version
Nothing to do
--2017-11-18 21:53:19--  https://github.com/wangyu-/UDPspeeder/releases/download/v1@20171116.0/speederv2_binaries.tar.gz
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-11-18 21:53:20 ERROR 404: Not Found.

 下载 UDPspeeder 失败！

**Comment by 233boy** [comment]
@zugust 
我马上更新一下

**Comment by zugust** [comment]
@233boy 多谢了，好像蛮多人都在等大大这个脚本呢

**Comment by 233boy** [comment]
@zugust 
看看能解决了吗

**Comment by 233boy** [comment]
@zugust 
请问解决问题了吗？
重新使用安装 命令 执行看看？我这边测试没有问题了
bash <(curl -s -L https://233abc.com/UDPspeeder.sh)

**Comment by zugust** [comment]
@233boy 解决了，安装完成！thx

**Comment by zugust** [comment]
但是如何配置...后台运行...开鸡启动这些东西嘛...我真的不会咋办(╥╯^╰╥)

**Comment by 233boy** [comment]
@zugust 
最简单方法，
在运行程序后面是一个 **&** 符号即可
比如说要运行的命令是
```
speederv2 xxxxx
```
那么修改成
```
speederv2 xxxxx &
```
运行之后 再按 Ctrl + C 退出，程序会在后台运行的。

**Comment by 233boy** [comment]
上面这个只是后台运行，开机启动的话，你自己谷歌搜索一下教程吧，自己动手，丰衣足食

**Comment by zugust** [comment]
好的，我再摸索一下，总之多谢了
