### ISSUE TITLE
由于 UDPspeeder 作者发布版本的原因，脚本目前安装的是 V1 版本，不是 V2

### ISSUE THREAD

**Issue by 233boy** [233boy/UDPspeeder#5]
@wangyu-
大佬，是否能固定一下最新版本是 V2 或者 V1

**Comment by wangyu-** [comment]
我发布了一个新的版本，现在V2是最后一个release了。你的脚本暂时应该没问题了。

不过现在V1和V2是在同一个repo的不同分支中，哪个最后发布了新版本，哪个就是最后一个release了。长远的办法是你在脚本里判断一下，过滤掉V1版的release。

**Comment by wangyu-** [comment]
>长远的办法是你在脚本里判断一下，过滤掉V1版的release。

暂时不改也问题不大，V1应该很少会发布新版本了。

**Comment by 233boy** [comment]
@wangyu- 
目前 latest 版本是 V1 的
脚本是根据 latest 来决定的，但是 V2 跟 V1 的文件存在着名称的差异，如果你的下一个最新版本是  V2，那么脚本肯定也会出问题了。
要不这样来吧，我想，以后应该都是 V2 版本了，
等你发布下一最新版本的时候，统一为 V2 版本的了，通知我一声，开个 issues 什么的，我更新一下脚本
怎么样？

**Comment by wangyu-** [comment]
>目前 latest 版本是 V1 的

可能因为我刚才把状态改成了pre-release的原因。 现在应该没问题了，latest是v2。

**Comment by 233boy** [comment]
@wangyu- 
脚本也更新了，也测试了，没有问题，谢谢哈
