### ISSUE TITLE
用梅林的固件连接udpspeeder和udp2raw无效

### ISSUE THREAD

**Issue by jyogyou** [233boy/UDPspeeder#6]
使用梅林的固件连接后，VPS端没有任何响应，反而玩游戏吃鸡点PLAY进不了游戏，单连udpspeederv2不行，串联就更不行，不知道为什么？

**Comment by 233boy** [comment]
@jyogyou 
你应该检查连接步骤，确保连接信息是否没有问题
备注，这个 脚本仅负责安装和卸载，连配置也没有可选提供，所以说除了安装和卸载之外你所遇到的任何问题都跟这个脚本木有关系的，如果你觉得是 udpspeeder 的问题，你可以尝试跟作者反馈。
反馈链接：[https://github.com/wangyu-/UDPspeeder](https://github.com/wangyu-/UDPspeeder)

**Comment by wangluyichen** [comment]
好吧，我也是上面的问题，加速游戏使用。。

**Comment by lhuac** [comment]
@wangluyichen 
跟脚本木有问题的，脚本只提供安装跟卸载，你应该检查连接配置参数是否正确，或者 VPS 的防火墙端口是否已经打开等
或者直接跟作者反馈：https://github.com/wangyu-/UDPspeeder
