### ISSUE TITLE
安装后无法运行

### ISSUE THREAD

**Issue by icetea0822** [233boy/UDPspeeder#7]
请问安装后输入speederv2为什么提示command not found呢？

**Comment by 233boy** [comment]
@icetea0822 
您好，请问你是什么系统呢？ CentOS 6?
我刚刚测试了一下，木有问题呢

**Comment by icetea0822** [comment]
是这个系统
CentOS release 6.9 (Final) 试了很多次都不行啊

**Comment by 233boy** [comment]
@icetea0822 
不用尝试了，是系统 的原因，我很抱歉
使用 `/usr/local/bin/speederv2` 启动即可

**Comment by icetea0822** [comment]
可以了！
非常感谢！
